### ISSUE TITLE
Doesn't work with ramda's lenses

### ISSUE THREAD

**Issue by Dartv** [hkwu/ghastly#2]
When `next` receives new context returned by ramda's lens method `over` or `set` the `handler` is never called. It propagates through all of middleware but never actually calls the `handler`.
Example:
```js
import R from 'ramda';

const middlewareA = () => async (next, context) => {
  const something = R.lensPath(['args', 'something']);
  const newContext = R.set(something, 'hello world', context);

  context.args.something = 'hello world';

  console.log(R.equals(context, newContext)); // true

  return next(newContext); // doesn't work
  // return next(context); // works
};

const middlewareB = () => async (next, context) => {
  console.log('logs');
  return next(context);
};

const handler = async () => 'Hello World!'; // never called

export default () => ({
  handler,
  middleware: [middlewareA(), middlewareB()],
  triggers: ['test'],
});

```
http://ramdajs.com/docs/#set

I guess it's some sort of inheritance problem.

**Comment by hkwu** [comment]
I'm not familiar with Rambda, so I'm just guessing here. But if the `newContext` is supposed to be a copy of `context` but with some properties changed, then it's possible that Rambda isn't copying all of the context properties. The `context` the handler receives is actually injected with "hidden" properties by the dispatcher (which I touched on in my comment in #1). As such the fix is probably the same.

I guess you didn't see any log errors when running this? Probably my fault, the dispatcher actually catches errors and emits something, but I never updated the docs to mention it. You can try adding a listener to the client:

```js
client.on('dispatchFail', (reason, context) => {
  console.log(reason, context);
});
```

That would help me narrow down where an error is happening.

**Comment by Dartv** [comment]
It should definitly be mentioned in docs. I was struggling with debugging because there were no errors at all.
Here is the error:
```js
error: TypeError: createDispatch is not a function
    at C:\web\discordbot\node_modules\ghastly\lib\command\CommandObject.js:116:24
    at C:/web/discordbot/src/commands/test.js:17:10
    at args (C:\web\discordbot\node_modules\ghastly\lib\core\apply.js:33:65)
    at C:/web/discordbot/src/commands/test.js:11:10
    at CommandObject.args [as handler] (C:\web\discordbot\node_modules\ghastly\lib\core\apply.js:33:65)
    at CommandObject.handle (C:\web\discordbot\node_modules\ghastly\lib\command\CommandObject.js:131:17)
    at Dispatcher.dispatch (C:\web\discordbot\node_modules\ghastly\lib\client\dispatcher\Dispatcher.js:202:30)
    at emitOne (events.js:115:13)
    at Ghastly.emit (events.js:210:7)
    at MessageCreateHandler.handle (C:\web\discordbot\node_modules\discord.js\src\client\websocket\packets\handlers\MessageCreate.js:9:34)
    at WebSocketPacketManager.handle (C:\web\discordbot\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:103:65)
    at WebSocketConnection.onPacket (C:\web\discordbot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:330:35)
    at WebSocketConnection.onMessage (C:\web\discordbot\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:293:17)
    at WebSocket.onMessage (C:\web\discordbot\node_modules\ws\lib\EventTarget.js:99:16)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
```

and the context:
```js
handlerError { message:
   Message {
     channel:
      TextChannel {
        type: 'text',
        id: '****',
        name: 'general',
        position: 0,
        permissionOverwrites: Collection {},
        topic: null,
        nsfw: false,
        lastMessageID: '365282113680834560',
        guild: [Object],
        messages: [Object],
        _typing: [Object],
        lastMessage: [Circular] },
     id: '365282113680834560',
     type: 'DEFAULT',
     content: 'k!test',
     author:
      User {
        id: '****',
        username: '****',
        discriminator: '****',
        avatar: '88e658537a713b9013a5303a8c2af1b7',
        bot: false,
        lastMessageID: '365282113680834560',
        lastMessage: [Circular] },
     member:
      GuildMember {
        guild: [Object],
        user: [Object],
        _roles: [],
        serverDeaf: false,
        serverMute: false,
        selfMute: undefined,
        selfDeaf: undefined,
        voiceSessionID: undefined,
        voiceChannelID: undefined,
        speaking: false,
        nickname: null,
        joinedTimestamp: 1506608266985,
        lastMessageID: '365282113680834560',
        lastMessage: [Circular] },
     pinned: false,
     tts: false,
     nonce: '365282110736433152',
     system: false,
     embeds: [],
     attachments: Collection {},
     createdTimestamp: 1507160442515,
     editedTimestamp: null,
     reactions: Collection {},
     mentions:
      MessageMentions {
        everyone: false,
        users: Collection {},
        roles: Collection {},
        _content: 'k!test',
        _client: [Object],
        _guild: [Object],
        _members: null,
        _channels: null },
     webhookID: null,
     hit: null,
     _edits: [] },
  command: 'test',
  args: { something: 'hello world' },
```

I changed a few fields to ****.

**Comment by Dartv** [comment]
And btw, if this library is marketing itself as declarative, shouldn't it work with functional programming? At least it should be mentioned in docs that changing context .

**Comment by Dartv** [comment]
And btw, `dispatchFail` emits on every command call, not just errors. When there is no error, the callback arguments are `prefixFilter` and `eventFilter`.

**Comment by hkwu** [comment]
Right, `eventFilter` is when the message is filtered because it was edited but the content didn't change. `prefixFilter` is when the message didn't match the prefix. Since the bot's messages are also heard it emits quite often. The intention was to have a single listener for `dispatchFail` which uses a `switch` on `reason` to handle just the errors it cares about.

**Comment by hkwu** [comment]
v0.4.0 may have fixed this. Follow up if there's still issues.

**Comment by Dartv** [comment]
Great work. Works fine now!
